export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM'
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM
export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM'
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM

export const FIELD_VAL_CHG = 'FIELD_VAL_CHG'
export type FIELD_VAL_CHG = typeof FIELD_VAL_CHG